name: Lint

on: [push, pull_request]

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: intl, mbstring
          php-version: 7.4
          tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ hashFiles('composer.json') }}
          restore-keys: composer-

      - name: Install dependencies
        id: install
        run: composer install

      - name: Lint YAML files
        run: bin/yaml-lint --parse-tags ./yaml

      - name: Lint from STDIN
        if: always() && steps.install.outcome == 'success'
        run: cat ./yaml/invalid-file.yaml | bin/yaml-lint --parse-tags -
